<?php
declare(strict_types=1);

/** @var \Revolut\PaymentHyva\Magewire\Checkout\Payment\Method\RevolutGooglePay $magewire */
/** @var \Magento\Framework\Escaper $escaper */

$quote = $magewire->getQuote();
?>
<div
    data-revolut-currency="<?= $escaper->escapeHtmlAttr($quote->getQuoteCurrencyCode()) ?>"
    data-revolut-amount="<?= $escaper->escapeHtmlAttr($quote->getGrandTotal()) ?>"
>
    <div id="revolut-google-pay-component" class="mt-4 min-h-[50px]" wire:ignore></div>
</div>
