<?php
declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Revolut\PaymentHyva\Magewire\Checkout\Payment\Method\RevolutCard $magewire */
?>
<div>
    <!-- Container for revolut card UI -->
    <div id="revolut-card-component" class="mt-4 border border-gray-300 rounded-md p-3 bg-white w-full min-h-[45px]" wire:ignore></div>
    <ul id="revolut-card-errors" class="text-red-600 mt-2 text-sm list-disc list-inside pl-2" style="display: none;"></ul>
</div>
